version: '2'

services:
  app:
    image: 'customer-management:latest'
    build:
      context: .
    container_name: customer-management
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customers
      - SPRING_DATASOURCE_USERNAME=pgteste
      - SPRING_DATASOURCE_PASSWORD=pgteste
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
         - POSTGRES_PASSWORD=pgteste
         - POSTGRES_USER=pgteste
         - POSTGRES_DB=customers
    restart: unless-stopped
